version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2023-03-13T19-46-17Z
    command: server --address ":9000" --console-address ":9001" /data
    env_file:
      - minio.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - traefik.http.routers.minio.entryPoints=minio
      - traefik.http.routers.minio.rule=Host(`minio.federation.home`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.service=minio-service
      - traefik.http.services.minio-service.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.entryPoints=minio-console
      - traefik.http.routers.minio-console.rule=Host(`minio-console.federation.home`)
      - traefik.http.routers.minio-console.tls=true
      - traefik.http.routers.minio-console.service=minio-console-service
      - traefik.http.services.minio-console-service.loadbalancer.server.port=9001
    networks:
      - web
    restart: unless-stopped
    user: "33:33"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    external: true

networks:
  web:
    external: true
  
